spring:
  config:
    import:
      - optional:file:.env[.properties]
  application:
    name: worklog
  datasource:
    url: jdbc:mysql://192.168.1.252:3306/worklog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 3020
  error:
    whitelabel:
      enabled: false

worklog:
  pdf:
    font-path: C:/Windows/Fonts/malgun.ttf
