import { useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './style.css'
import './meeting.css'
import { CatalogManager, ScheduleQuickForm } from './scheduler'

const ko = { title:'\uc5c5\ubb34\uc77c\uc9c0', filter:'SRGH IT', request:'\uc694\uccad \uc0dd\uc131', dark:'\ub2e4\ud06c', light:'\ub77c\uc774\ud2b8', apply:'\uc801\uc6a9\ud558\uae30', save:'\uc800\uc7a5', complete:'\uc791\uc131 \uc644\ub8cc', date:'\ub0a0\uc9dc', processor:'\ucc98\ub9ac\uc790', keyword:'\uac80\uc0c9\uc5b4', content:'\uc694\uccad \ub0b4\uc6a9', requester:'\uc694\uccad\uc790', extension:'\ub0b4\uc120 \ubc88\ud638', department:'\ubd80\uc11c', major:'\uba54\uc778 \uce74\ud14c\uace0\ub9ac', minor:'\uc11c\ube0c \uce74\ud14c\uace0\ub9ac' }
const localDate = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const today = () => localDate(new Date())
const threeMonthsAgo = () => { const date = new Date(); date.setMonth(date.getMonth() - 3); return localDate(date) }
const formatDate = value => value ? `${value.slice(2, 4)}.${value.slice(5, 7)}.${value.slice(8, 10)}` : '-'
const isoDate = localDate
const addMonths = (date, amount) => new Date(date.getFullYear(), date.getMonth() + amount, 1)
const cellButtonStyle = { border: 0, background: 'none', padding: 0, color: 'inherit', font: 'inherit', textAlign: 'left', cursor: 'pointer' }
const emptyCreate = () => ({ request_date: today(), major_category: '', minor_category: '', department: '', requester: '', requester_extension: '', request_content: '' })

function App() {
  const [data, setData] = useState(null)
  const [filters, setFilters] = useState({ from: threeMonthsAgo(), to: today(), processor: '', keyword: '' })
  const [dark, setDark] = useState(() => localStorage.getItem('worklog-dark-mode') === 'true')
  const [filterOpen, setFilterOpen] = useState(false), [createOpen, setCreateOpen] = useState(false), [editingRequest, setEditingRequest] = useState(null), [processing, setProcessing] = useState(null), [showInProgress, setShowInProgress] = useState(true), [meetingMode, setMeetingMode] = useState(false)
  const load = async (next = filters) => { const params = new URLSearchParams(Object.entries(next).filter(([, value]) => value !== '')); const response = await fetch(`/api/worklogs?${params}`, { cache: 'no-store' }); if (response.ok) setData(await response.json()); else alert('\ub370\uc774\ud130\ub97c \ubd88\ub7ec\uc624\uc9c0 \ubabb\ud588\uc2b5\ub2c8\ub2e4.') }
  useEffect(() => { load() }, [])
  useEffect(() => { const stream = new EventSource('/api/events/worklogs'); const refresh = () => load(); stream.addEventListener('worklog-update', refresh); return () => stream.close() }, [filters])
  useEffect(() => { document.body.classList.toggle('dark', dark); localStorage.setItem('worklog-dark-mode', dark) }, [dark])
  useEffect(() => { const followPointer = event => { document.documentElement.style.setProperty('--tooltip-x', `${event.clientX + 14}px`); document.documentElement.style.setProperty('--tooltip-y', `${event.clientY + 16}px`) }; window.addEventListener('pointermove', followPointer); return () => window.removeEventListener('pointermove', followPointer) }, [])
  useEffect(() => { const colors = { '\uae40\uc7ac\ud604': dark ? '#7f1d1d' : '#fecaca', '\uac15\uc131\uad6c': dark ? '#1e3a8a' : '#bfdbfe', '\uc624\uc138\ubbfc': dark ? '#14532d' : '#bbf7d0', '\ucd5c\uc778\ud638': dark ? '#581c87' : '#e9d5ff' }; document.querySelectorAll('tbody tr td:nth-child(5) button').forEach(button => { const name = button.textContent.trim(); if (!name) return; const stroke = colors[name] || (dark ? '#334155' : '#e2e8f0'); button.style.background = `linear-gradient(transparent 38%, ${stroke} 38% 88%, transparent 88%)`; button.style.color = dark ? '#f8fafc' : 'inherit'; button.style.padding = '0 4px'; button.style.borderRadius = '2px' }) }, [data, dark])
  const updateFilters = patch => { const next = { ...filters, ...patch }; setFilters(next); load(next) }
  const closeSidePanels = () => { setCreateOpen(false); setEditingRequest(null); setProcessing(null) }
  const closeAllPanels = () => { closeSidePanels(); setFilterOpen(false); setMeetingMode(false) }
  const closeOnOuterArea = event => { if (event.target.closest('.filter-panel, .create-panel, .drawer-tab, .table-wrap')) return; closeAllPanels() }
  const toggleFilterPanel = () => { if (filterOpen) setMeetingMode(false); setFilterOpen(!filterOpen) }
  const openRequestEditor = (event, item) => { event.stopPropagation(); setEditingRequest(item); setCreateOpen(false); setProcessing(null) }
  const openProcessing = (event, item) => { event.stopPropagation(); setProcessing(item); setCreateOpen(false); setEditingRequest(null) }
  const rightPanelOpen = createOpen || editingRequest || processing
  const visibleItems = data?.items
  const inProgressCount = data?.items.filter(item => !item.processing_date).length ?? 0
  const remove = async id => { if (!confirm('\uc774 \uc694\uccad\uc744 \uc0ad\uc81c\ud560\uae4c\uc694?')) return; await fetch(`/api/worklogs/${id}`, { method: 'DELETE' }); load() }
  if (!data) return <div className="loading">Loading...</div>
  return <main className="page" onClick={closeOnOuterArea}>
    <header><div><p className="eyebrow">SRGH IT Team</p><h1>{ko.title}</h1></div></header>
    <button className={`drawer-tab filter-tab ${filterOpen ? 'open' : ''}`} style={{ left: filterOpen ? '320px' : 0 }} onClick={toggleFilterPanel} aria-label="filter">{filterOpen ? '‹' : '›'}</button>
    <aside className={`filter-panel ${filterOpen ? 'open' : ''}`}><div className="panel-head"><h2>{meetingMode ? '\ud68c\uc758\ub85d \uc791\uc131' : ko.filter}</h2><button className="theme-toggle" onClick={() => setDark(!dark)}>{dark ? `☀` : `🌙`}</button></div>{meetingMode ? <MeetingForm processors={data.processors} onDone={() => setMeetingMode(false)}/> : <><FilterForm filters={filters} processors={data.processors} onChange={updateFilters}/><ScheduleQuickForm/><div className="panel-bottom-actions"><button className="meeting-button" onClick={() => setMeetingMode(true)}>{'\ud68c\uc758\ub85d'}</button></div></>}</aside>
    <button className={`drawer-tab create-tab ${rightPanelOpen ? 'open' : ''}`} style={{ right: rightPanelOpen ? '320px' : 0 }} onClick={() => { if (rightPanelOpen) closeSidePanels(); else setCreateOpen(true) }} aria-label="create">{rightPanelOpen ? '›' : '‹'}</button>
    <aside className={`create-panel ${createOpen ? 'open' : ''}`}><div className="panel-head"><h2>{ko.request}</h2></div><RequestForm data={data} onSaved={() => { setCreateOpen(false); load() }}/></aside>
    <aside className={`create-panel ${editingRequest ? 'open' : ''}`}><div className="panel-head"><h2>{'\uc694\uccad \uc218\uc815'}</h2></div>{editingRequest && <RequestForm key={editingRequest.id} data={data} item={editingRequest} onSaved={() => { setEditingRequest(null); load() }}/>}</aside>
    <aside className={`create-panel ${processing ? 'open' : ''}`}><div className="panel-head"><h2>{'\uc694\uccad \ucc98\ub9ac'}</h2></div>{processing && <ProcessingForm key={processing.id} item={processing} processors={data.processors} onSaved={() => { setProcessing(null); load() }}/>}</aside>
    <section className={`table-wrap ${showInProgress ? '' : 'hide-in-progress'}`}><table><colgroup><col className="date-col"/><col className="category-col"/><col className="requester-col"/><col className="request-content-col"/><col className="processor-col"/><col className="processing-content-col"/><col className="status-col"/></colgroup><thead><tr><th>{ko.date}</th><th>{'\uce74\ud14c\uace0\ub9ac'}</th><th>{ko.department}</th><th>{ko.content}</th><th>{ko.processor}</th><th>{'\ucc98\ub9ac \ub0b4\uc6a9'}</th><th><button className="progress-toggle" onClick={() => setShowInProgress(!showInProgress)} title={'\uc9c4\ud589\uc911 \ubaa9\ub85d \uc811\uae30/\ud3bc\uce58\uae30'}>{inProgressCount}</button></th></tr></thead><tbody onClick={closeSidePanels}>
      {!visibleItems.length && <tr><td colSpan="7" className="empty">{'\uc870\uac74\uc5d0 \ub9de\ub294 \uc694\uccad\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.'}</td></tr>}
      {visibleItems.map(item => <tr key={item.id} className={item.processing_date ? '' : 'in-progress-row'}><td className="editable-cell" onClick={event => openRequestEditor(event, item)}><button style={cellButtonStyle} className="date-tooltip">{formatDate(item.processing_date || item.timestamp || item.request_date)}<span className="tooltip-content"><b>{ko.date}</b>{formatDate(item.request_date)}<b>{'\uc218\uc815 \ub0a0\uc9dc'}</b>{item.timestamp || '-'}<b>{'\ucc98\ub9ac \ub0a0\uc9dc'}</b>{formatDate(item.processing_date)}</span></button></td><td className="editable-cell" onClick={event => openRequestEditor(event, item)}><button style={cellButtonStyle} className="category-tooltip">{data.majorNames[item.major_category]}<span className="tooltip-content"><b>{ko.major}</b>{data.majorNames[item.major_category]}<b>{ko.minor}</b>{data.minorNames[item.minor_category]}</span></button></td><td className="editable-cell" onClick={event => openRequestEditor(event, item)}><button style={cellButtonStyle} className="requester-tooltip">{data.departmentNames[item.department]}<span className="tooltip-content"><b>{ko.department}</b>{data.departmentNames[item.department]}<b>{ko.requester}</b>{item.requester}<b>{ko.extension}</b>{item.requester_extension}</span></button></td><td className="content editable-cell" onClick={event => openRequestEditor(event, item)}><button style={cellButtonStyle}>{item.request_content}</button></td><td className="editable-cell" onClick={event => openProcessing(event, item)}><button style={cellButtonStyle}>{item.processor ? data.processorNames[item.processor] : ''}</button></td><td className="editable-cell" onClick={event => openProcessing(event, item)}><button style={cellButtonStyle}>{item.processing_content || ''}</button></td><td><span className={`status-icon ${item.processing_date ? 'done' : 'progress'}`} onClick={event => { event.stopPropagation(); remove(item.id) }} style={{ ...(item.processing_date ? { background: '#0f766e', color: '#fff', boxShadow: '0 2px 6px #0f766e55' } : { background: '#eef2ff', color: '#4f46e5', border: '1px solid #a5b4fc' }), cursor: 'pointer' }} title={item.processing_date ? '\ucc98\ub9ac\uc644\ub8cc' : '\uc9c4\ud589\uc911'}>{item.processing_date ? '✓' : '◷'}</span></td></tr>)}
    </tbody></table></section>
  </main>
}

function FilterForm({ filters, processors, onChange }) { return <div className="filters"><label>{'\uc870\ud68c \uae30\uac04'}<DateRangePicker from={filters.from} to={filters.to} onChange={(from, to) => onChange({ from, to })}/></label><label>{ko.processor}<select value={filters.processor} onChange={e => onChange({ processor: e.target.value })}><option value="">{'\uc804\uccb4'}</option>{processors.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{ko.keyword}<input value={filters.keyword} onChange={e => onChange({ keyword: e.target.value })} placeholder={'\uc694\uccad\uc790, \ub0b4\uc6a9, \uce74\ud14c\uace0\ub9ac \uac80\uc0c9'}/></label></div> }
function DateRangePicker({ from, to, onChange }) { const [open, setOpen] = useState(false), [month, setMonth] = useState(() => new Date()), [yearPicker, setYearPicker] = useState(null), [draftFrom, setDraftFrom] = useState(from), [draftTo, setDraftTo] = useState(to), pickerRef = useRef(null); useEffect(() => { if (!open) return; const close = event => { if (!pickerRef.current?.contains(event.target)) setOpen(false) }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close) }, [open]); const toggle = () => { if (!open) { setDraftFrom(from); setDraftTo(to) } setOpen(!open) }; const choose = value => { if (!draftFrom || draftTo || value < draftFrom) { setDraftFrom(value); setDraftTo('') } else setDraftTo(value) }; const changeYear = (index, year) => { const target = index === 0 ? month : addMonths(month, 1); const replacement = new Date(year, target.getMonth(), 1); setMonth(index === 0 ? replacement : addMonths(replacement, -1)); setYearPicker(null) }; const reset = () => { setDraftFrom(threeMonthsAgo()); setDraftTo(today()) }; const confirm = () => { onChange(draftFrom, draftTo); setOpen(false) }; const label = `${formatDate(from)} ~ ${formatDate(to)}`; return <div className="range-picker" ref={pickerRef}><button type="button" className="range-button" onClick={toggle}><span>{label}</span><span className="calendar-icon">&#128197;</span></button>{open && <div className="calendar-popover"><div className="calendar-nav"><button type="button" onClick={() => setMonth(addMonths(month, -1))}>‹</button><span>{'\ub0a0\uc9dc \ubc94\uc704 \uc120\ud0dd'}</span><button type="button" onClick={() => setMonth(addMonths(month, 1))}>›</button></div><div className="calendar-pair"><Calendar month={month} from={draftFrom} to={draftTo} onChoose={choose} showYears={yearPicker === 0} onToggleYear={() => setYearPicker(yearPicker === 0 ? null : 0)} onYearChange={year => changeYear(0, year)}/><Calendar month={addMonths(month, 1)} from={draftFrom} to={draftTo} onChoose={choose} showYears={yearPicker === 1} onToggleYear={() => setYearPicker(yearPicker === 1 ? null : 1)} onYearChange={year => changeYear(1, year)}/></div><div className="manual-range"><input type="date" value={draftFrom} onChange={e => { setDraftFrom(e.target.value); setDraftTo('') }}/><span>~</span><input type="date" value={draftTo} min={draftFrom} onChange={e => setDraftTo(e.target.value)}/></div><div className="calendar-actions"><button type="button" className="clear-range" onClick={reset}>{'\ucd08\uae30\ud654'}</button><button type="button" className="confirm-range" onClick={confirm}>{'\ud655\uc778'}</button></div></div>}</div> }
function Calendar({ month, from, to, onChoose, showYears, onToggleYear, onYearChange }) { const first = new Date(month.getFullYear(), month.getMonth(), 1), lastDay = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(), cells = Array(first.getDay()).fill(null).concat(Array.from({ length: lastDay }, (_, index) => new Date(month.getFullYear(), month.getMonth(), index + 1))), years = Array.from({ length: 15 }, (_, index) => month.getFullYear() - 7 + index); return <div className="calendar"><button type="button" className="calendar-title" onClick={onToggleYear}>{month.getFullYear()}.{String(month.getMonth() + 1).padStart(2, '0')}</button>{showYears ? <div className="year-grid">{years.map(year => <button type="button" key={year} className={year === month.getFullYear() ? 'selected' : ''} onClick={() => onYearChange(year)}>{year}</button>)}</div> : <><div className="weekdays">{['S','M','T','W','T','F','S'].map((day, index) => <span className={index === 0 ? 'sun' : index === 6 ? 'sat' : ''} key={`${day}${index}`}>{day}</span>)}</div><div className="days">{cells.map((day, index) => { if (!day) return <i key={index}/>; const value = isoDate(day), selected = value === from || value === to, inRange = from && to && value > from && value < to; return <button type="button" key={value} className={`${selected ? 'selected' : ''} ${inRange ? 'in-range' : ''}`} onClick={() => onChoose(value)}>{day.getDate()}</button> })}</div></>}</div> }
function Modal({ title, children, onClose }) { return <div className="modal"><div className="dialog"><button className="close" onClick={onClose}>×</button><h2>{title}</h2>{children}</div></div> }
function CategoryField({ label, options, value, setValue }) { return <label>{label}<select value={value} onChange={e => setValue(e.target.value)} required><option value="">{'\uc120\ud0dd\ud558\uc138\uc694'}</option>{options.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label> }
function RequestForm({ data, item, onSaved }) { const initial = item ? { request_date: item.request_date, major_category: String(item.major_category), minor_category: String(item.minor_category), department: String(item.department), requester: item.requester, requester_extension: item.requester_extension, request_content: item.request_content } : emptyCreate(); const [form, setForm] = useState(initial); const update = (key, value) => setForm({ ...form, [key]: value }); const submit = async e => { e.preventDefault(); const response = await fetch(item ? `/api/worklogs/${item.id}` : '/api/worklogs', { method: item ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!response.ok) return alert('\uc694\uccad \uc800\uc7a5\uc5d0 \uc2e4\ud328\ud588\uc2b5\ub2c8\ub2e4.'); onSaved() }; return <form className="create-form" onSubmit={submit}><label>{ko.date}<input type="date" value={form.request_date} onChange={e => update('request_date', e.target.value)} required/></label><CategoryField label={ko.major} options={data.majors} value={form.major_category} setValue={v => update('major_category', v)}/><CategoryField label={ko.minor} options={data.minors} value={form.minor_category} setValue={v => update('minor_category', v)}/><CategoryField label={ko.department} options={data.departments} value={form.department} setValue={v => update('department', v)}/><label>{ko.requester}<input value={form.requester} onChange={e => update('requester', e.target.value)} required/></label><label>{ko.extension}<input value={form.requester_extension} onChange={e => update('requester_extension', e.target.value)} required/></label><label>{ko.content}<textarea value={form.request_content} onChange={e => update('request_content', e.target.value)} required/></label><div className="actions"><button className="primary">{ko.complete}</button></div></form> }
function ProcessingForm({ item, processors, onSaved }) { const [form, setForm] = useState({ processor: item.processor || '', processing_date: item.processing_date || '', processing_content: item.processing_content || '' }); const submit = async e => { e.preventDefault(); const body = { ...form, processor: form.processor ? Number(form.processor) : null, processing_date: form.processing_date || null }; const response = await fetch(`/api/worklogs/${item.id}/processing`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) return alert('\uc800\uc7a5\uc5d0 \uc2e4\ud328\ud588\uc2b5\ub2c8\ub2e4.'); onSaved() }; return <form className="create-form" onSubmit={submit}><label>{ko.processor}<select value={form.processor} onChange={e => setForm({ ...form, processor: e.target.value })}><option value="">{'\ubbf8\uc9c0\uc815'}</option>{processors.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{'\ucc98\ub9ac \ub0a0\uc9dc'}<input type="date" value={form.processing_date} onChange={e => setForm({ ...form, processing_date: e.target.value })}/></label><label>{'\ucc98\ub9ac \ub0b4\uc6a9'}<textarea value={form.processing_content} onChange={e => setForm({ ...form, processing_content: e.target.value })}/></label><div className="actions"><button className="primary">{ko.complete}</button></div></form> }
function MeetingForm({ processors, onDone }) { const [date, setDate] = useState(today()), [author, setAuthor] = useState(''), [notice, setNotice] = useState(''), [absenceReason, setAbsenceReason] = useState(''), [attendees, setAttendees] = useState(() => processors.map(p => ({ name: p.name, present: true }))); const save = async e => { e.preventDefault(); const response = await fetch('/api/worklogs/meeting-minutes/pdf', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ meeting_date: date, author, attendees: attendees.map(a => ({ ...a, reason: a.present ? '' : absenceReason })), notice }) }); if (!response.ok) return alert('PDF \uc0dd\uc131\uc5d0 \uc2e4\ud328\ud588\uc2b5\ub2c8\ub2e4.'); const url = URL.createObjectURL(await response.blob()), link = document.createElement('a'); link.href = url; link.download = `\ud68c\uc758\ub85d_${date}.pdf`; link.click(); URL.revokeObjectURL(url); onDone() }; const toggle = index => setAttendees(attendees.map((a, i) => i === index ? { ...a, present: !a.present } : a)); return <form className="create-form" onSubmit={save}><label>{'\ud68c\uc758 \ub0a0\uc9dc'}<input type="date" value={date} onChange={e => setDate(e.target.value)} required/></label><label>{'\uc791\uc131\uc790'}<select value={author} onChange={e => setAuthor(e.target.value)} required><option value="">{'\uc120\ud0dd\ud558\uc138\uc694'}</option>{processors.map(p => <option key={p.id} value={p.name}>{p.name}</option>)}</select></label><label>{'\ucc38\uc11d\uc790'}<div className="attendees">{attendees.map((a, i) => <div className="attendee-row" key={a.name}><span className="attendee-name">{a.name}</span><button type="button" className={a.present ? 'attendance present' : 'attendance absent'} onClick={() => toggle(i)}>{a.present ? '\ucc38\uc11d' : '\ubd88\ucc38'}</button></div>)}</div></label><label>{'\uacb0\uc11d \uc0ac\uc720'}<input value={absenceReason} onChange={e => setAbsenceReason(e.target.value)}/></label><label>{'\uc54c\ub9bc\uc0ac\ud56d'}<textarea value={notice} onChange={e => setNotice(e.target.value)}/></label><div className="actions"><button className="primary">{ko.complete}</button></div></form> }
createRoot(document.getElementById('root')).render(window.location.pathname === '/admin' ? <CatalogManager/> : <App />)
