import { Fragment, useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './style.css'
import './meeting.css'
import { CatalogManager, ScheduleQuickForm } from './scheduler'

const ko = { title: '업무일지', filter: 'SRGH IT', request: '요청 생성', complete: '작성 완료', date: '날짜', processor: '처리자', keyword: '검색어', content: '요청 내용', requester: '요청자', extension: '내선 번호', department: '부서', major: '메인 카테고리', minor: '서브 카테고리' }
const localDate = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const today = () => localDate(new Date())
const weekAgo = () => { const value = new Date(); value.setDate(value.getDate() - 6); return localDate(value) }
const monthAgo = () => { const value = new Date(); value.setMonth(value.getMonth() - 1); return localDate(value) }
const shiftDate = (value, days) => { const date = new Date(`${value}T00:00:00`); date.setDate(date.getDate() + days); return localDate(date) }
const moveDateBack = (value, days = 0, months = 0, years = 0) => { const date = new Date(`${value}T00:00:00`); date.setDate(date.getDate() - days); date.setMonth(date.getMonth() - months); date.setFullYear(date.getFullYear() - years); return localDate(date) }
const formatDate = value => value ? `${value.slice(2, 4)}.${value.slice(5, 7)}.${value.slice(8, 10)}` : '-'
const timestampFormatter = new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Seoul', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: 'h23' })
const formatTimestamp = value => {
  if (!value) return '-'
  const hasTimezone = /(?:Z|[+-]\d{2}:\d{2})$/i.test(value)
  if (!hasTimezone) {
    const match = value.match(/^(\d{4}-\d{2}-\d{2})T(\d{2}:\d{2}:\d{2})/)
    if (match) return `${match[1]} ${match[2]}`
  }
  return timestampFormatter.format(new Date(value))
}
const formatLegacyTimestamp = value => formatTimestamp(value).replace(/^(\d{4})-(\d{2})-(\d{2})/, (_, year, month, day) => `${year.slice(2)}.${month}.${day}`)
const processorHighlight = (name, dark) => ({ 김재현: dark ? '#7f1d1d' : '#fecaca', 강성구: dark ? '#1e3a8a' : '#bfdbfe', 오세민: dark ? '#14532d' : '#bbf7d0', 최인호: dark ? '#581c87' : '#e9d5ff' }[name] || (dark ? '#334155' : '#e2e8f0'))
const legacyProcessorHighlight = name => !name ? 'transparent' : ({ 김재현: '#2F4F4F', 강성구: '#006400', 최인호: '#47007B', 오세민: '#00B9F2' }[name] || '#475569')
const addMonths = (date, amount) => new Date(date.getFullYear(), date.getMonth() + amount, 1)
const emptyCreate = () => ({ request_date: today(), major_category: '', minor_category: '', department: '', requester: '', requester_extension: '', request_content: '' })
const keepFloatingVisible = (position, node) => {
  const width = node?.offsetWidth || 360, height = node?.offsetHeight || 300
  return { x: Math.max(10, Math.min(position.x, window.innerWidth - width - 10)), y: Math.max(10, Math.min(position.y, window.innerHeight - height - 10)) }
}
const currentMonthSchedulePending = items => {
  const currentMonth = new Date(); currentMonth.setDate(1); currentMonth.setHours(0, 0, 0, 0)
  return items.filter(item => {
    if (item.completed) return false
    const start = new Date(`${item.start_date}T00:00:00`), step = Number(item.period_months || 0)
    if (!step) return start.getFullYear() === currentMonth.getFullYear() && start.getMonth() === currentMonth.getMonth()
    let occurrence = new Date(start)
    while (occurrence < currentMonth) occurrence = new Date(occurrence.getFullYear(), occurrence.getMonth() + step, Math.min(start.getDate(), new Date(occurrence.getFullYear(), occurrence.getMonth() + step + 1, 0).getDate()))
    return occurrence.getFullYear() === currentMonth.getFullYear() && occurrence.getMonth() === currentMonth.getMonth()
  }).length
}

function App() {
  const [data, setData] = useState(null)
  const [filters, setFilters] = useState({ from: monthAgo(), to: today(), processor: '', keyword: '', major: '', minor: '', department: '', requestContent: '' })
  const [dark, setDark] = useState(() => localStorage.getItem('worklog-dark-mode') === 'true')
  const [legacyMode, setLegacyMode] = useState(() => localStorage.getItem('worklog-legacy-mode') === 'true')
  const [fontScale, setFontScale] = useState(() => {
    const saved = Number(localStorage.getItem('worklog-font-scale'))
    return Number.isFinite(saved) ? Math.min(140, Math.max(100, saved)) : 100
  })
  const [editingRequest, setEditingRequest] = useState(null)
  const [processing, setProcessing] = useState(null)
  const [floating, setFloating] = useState(null)
  const [openDates, setOpenDates] = useState({})
  const doneStickyKey = useRef('')
  const doneStickyLabel = useRef(null)
  const doneStickyCount = useRef(null)
  const doneDateRows = useRef([])
  const [progressOpen, setProgressOpen] = useState(true)
  const [floatingPosition, setFloatingPosition] = useState(() => JSON.parse(localStorage.getItem('worklog-floating-position') || 'null'))
  const clientId = useRef(globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`)
  const pendingLocalMutation = useRef(false)
  const loadMoreRef = useRef(null)
  const scrollToDoneAfterFilter = useRef(false)
  const [loadingOlder, setLoadingOlder] = useState(false)
  const [hasMoreOlder, setHasMoreOlder] = useState(true)
  const [schedulePending, setSchedulePending] = useState(0)
  const load = async (next = filters) => { const params = new URLSearchParams(Object.entries(next).filter(([, value]) => value !== '')); const response = await fetch(`/api/worklogs?${params}`, { cache: 'no-store' }); if (response.ok) setData(await response.json()) }

  useEffect(() => { load() }, [])
  useEffect(() => { fetch('/api/schedules/admin').then(response => response.ok ? response.json() : []).then(items => setSchedulePending(currentMonthSchedulePending(items))).catch(() => {}) }, [])
  useEffect(() => { const stream = new EventSource('/api/events/worklogs'); const refresh = event => { if (event.data === 'connected') return; try { const update = JSON.parse(event.data); if (update.sourceClientId === clientId.current) { pendingLocalMutation.current = false; return } setData(previous => { if (!previous) return previous; if (update.deletedId != null) return { ...previous, items: previous.items.filter(item => item.id !== update.deletedId) }; const saved = update.item; if (!saved) return previous; const items = previous.items.some(item => item.id === saved.id) ? previous.items.map(item => item.id === saved.id ? saved : item) : [saved, ...previous.items]; return { ...previous, items: [...items].sort((left, right) => Number(Boolean(left.processing_date)) - Number(Boolean(right.processing_date))) } }) } catch { /* Older server events are ignored instead of causing a full reload. */ } }; stream.addEventListener('worklog-update', refresh); return () => stream.close() }, [])
  useEffect(() => { document.body.classList.toggle('dark', dark); localStorage.setItem('worklog-dark-mode', dark) }, [dark])
  useEffect(() => { localStorage.setItem('worklog-legacy-mode', legacyMode) }, [legacyMode])
  useEffect(() => {
    if (legacyMode) return
    let frame = 0
    const rows = [...document.querySelectorAll('.date-group-row[data-status="done"]')]
    const updateDoneDate = () => {
      const completed = document.getElementById('done-list')
      let active = null
      if (completed && completed.getBoundingClientRect().top <= 130) {
        for (const row of rows) {
          if (row.getBoundingClientRect().top <= 170) active = row
          else break
        }
      }
      const key = active ? `${active.dataset.date}-${active.dataset.count}` : ''
      if (key === doneStickyKey.current) return
      doneStickyKey.current = key
      if (doneStickyLabel.current) {
        doneStickyLabel.current.textContent = active ? `완료일 ${formatDate(active.dataset.date)}` : ''
        doneStickyLabel.current.classList.toggle('visible', Boolean(active))
      }
      if (doneStickyCount.current) doneStickyCount.current.textContent = active ? active.dataset.count : ''
    }
    const onScroll = () => { if (!frame) frame = requestAnimationFrame(() => { frame = 0; updateDoneDate() }) }
    updateDoneDate()
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => { window.removeEventListener('scroll', onScroll); cancelAnimationFrame(frame) }
  }, [data, legacyMode])
  useEffect(() => { document.documentElement.style.setProperty('--app-font-scale', `${fontScale / 100}`); localStorage.setItem('worklog-font-scale', String(fontScale)) }, [fontScale])
  useEffect(() => { localStorage.setItem('worklog-floating-position', JSON.stringify(floatingPosition)) }, [floatingPosition])
  useEffect(() => { const close = event => { if (event.key === 'Escape' && floating) setFloating(null) }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [floating])
  useEffect(() => { const submitOnEnter = event => { if (event.key !== 'Enter' || event.shiftKey || event.target instanceof HTMLTextAreaElement || !['request', 'request-edit', 'processing'].includes(floating)) return; const windowNode = document.activeElement?.closest('.floating-window'); if (!windowNode) return; event.preventDefault(); windowNode.querySelector('form')?.requestSubmit() }; window.addEventListener('keydown', submitOnEnter); return () => window.removeEventListener('keydown', submitOnEnter) }, [floating])
  useEffect(() => { const submitFloatingForm = event => { if (event.key !== 'Enter' || event.target instanceof HTMLTextAreaElement || !['request', 'request-edit', 'processing'].includes(floating)) return; const form = document.querySelector('.floating-window form'); if (!form) return; event.preventDefault(); event.stopImmediatePropagation(); form.requestSubmit() }; window.addEventListener('keydown', submitFloatingForm, true); return () => window.removeEventListener('keydown', submitFloatingForm, true) }, [floating])
  useEffect(() => { const growTextarea = event => { const textarea = event.target; if (!(textarea instanceof HTMLTextAreaElement) || !textarea.classList.contains('work-content-input')) return; textarea.style.height = 'auto'; textarea.style.height = `${textarea.scrollHeight}px` }; document.addEventListener('input', growTextarea); return () => document.removeEventListener('input', growTextarea) }, [])
  useEffect(() => { let frame = 0; doneDateRows.current = [...document.querySelectorAll('.date-group-row[data-status="done"]')]; const update = () => { const completed = document.getElementById('done-list'), rows = doneDateRows.current; let active = null; if (completed && completed.getBoundingClientRect().top <= 130) { let low = 0, high = rows.length - 1; while (low <= high) { const middle = (low + high) >> 1; if (rows[middle].getBoundingClientRect().top <= 170) { active = rows[middle]; low = middle + 1 } else high = middle - 1 } } const key = active ? `${active.dataset.date}-${active.dataset.count}` : ''; if (key === doneStickyKey.current) return; doneStickyKey.current = key; if (doneStickyLabel.current) { doneStickyLabel.current.textContent = active ? `완료일 ${formatDate(active.dataset.date)}` : ''; doneStickyLabel.current.classList.toggle('visible', Boolean(active)) } if (doneStickyCount.current) doneStickyCount.current.textContent = active ? active.dataset.count : '' }; const schedule = () => { if (frame) return; frame = requestAnimationFrame(() => { frame = 0; update() }) }; update(); window.addEventListener('scroll', schedule, { passive: true }); return () => { window.removeEventListener('scroll', schedule); cancelAnimationFrame(frame) } }, [data])
  useEffect(() => { if (!scrollToDoneAfterFilter.current) return; scrollToDoneAfterFilter.current = false; requestAnimationFrame(() => document.getElementById('latest-done-content')?.scrollIntoView({ behavior: 'smooth', block: 'start' })) }, [data])

  const updateFilters = (patch, moveToDone = true) => { const doneList = document.getElementById('done-list'); const viewingDone = Boolean(doneList && doneList.getBoundingClientRect().top <= 180); scrollToDoneAfterFilter.current = moveToDone && !viewingDone; const next = { ...filters, ...patch }; setHasMoreOlder(true); setFilters(next); load(next) }
  const resetFilters = () => updateFilters({ from: monthAgo(), to: today(), processor: '', keyword: '', major: '', minor: '', department: '', requestContent: '' }, false)
  const loadOlder = async () => { if (loadingOlder || !hasMoreOlder || !data) return; const olderTo = shiftDate(filters.from, -1), olderFrom = shiftDate(olderTo, -6), next = { ...filters, from: olderFrom, to: olderTo }; setLoadingOlder(true); try { const params = new URLSearchParams(Object.entries(next).filter(([, value]) => value !== '')); const response = await fetch(`/api/worklogs?${params}`, { cache: 'no-store' }); if (!response.ok) return; const page = await response.json(); const existing = new Set(data.items.map(item => item.id)), additions = page.items.filter(item => !existing.has(item.id)); if (!additions.length) { setHasMoreOlder(false); return } setData(previous => previous ? { ...previous, items: [...previous.items, ...additions] } : previous); setFilters(current => ({ ...current, from: olderFrom })) } finally { setLoadingOlder(false) } }
  useEffect(() => { const target = loadMoreRef.current; if (!target || !hasMoreOlder) return; const observer = new IntersectionObserver(entries => { if (entries[0].isIntersecting) loadOlder() }, { rootMargin: '280px 0px' }); observer.observe(target); return () => observer.disconnect() }, [data, filters, loadingOlder, hasMoreOlder])
  const openRequestEditor = (event, item) => { event.stopPropagation(); setEditingRequest(item); setProcessing(null); setFloating('request-edit') }
  const openProcessing = (event, item) => { event.stopPropagation(); setProcessing(item); setEditingRequest(null); setFloating('processing') }
  const applySavedItem = saved => { pendingLocalMutation.current = false; setData(previous => { if (!previous) return previous; const items = previous.items.some(item => item.id === saved.id) ? previous.items.map(item => item.id === saved.id ? saved : item) : [saved, ...previous.items]; return { ...previous, items: [...items].sort((left, right) => Number(Boolean(left.processing_date)) - Number(Boolean(right.processing_date))) } }) }
  const remove = async id => { if (!confirm('이 요청을 삭제할까요?')) return; const response = await fetch(`/api/worklogs/${id}`, { method: 'DELETE', headers: { 'X-Worklog-Client': clientId.current } }); if (response.ok) setData(previous => previous ? { ...previous, items: previous.items.filter(item => item.id !== id) } : previous) }
  const groups = useMemo(() => groupItems(data?.items || []), [data])
  if (!data) return <div className="loading">불러오는 중…</div>

  const groupKey = (status, date) => `${status}-${date}`
  const renderRows = (status, items, collapsible = true, showDate = true) => {
    if (!showDate) return items.map(item => <WorklogRow key={item.id} item={item} data={data} dark={dark} onRequest={openRequestEditor} onProcessing={openProcessing} onRemove={remove}/>)
    const byDate = groupByDate(items)
    return Object.entries(byDate).map(([date, rows], groupIndex) => <Fragment key={groupKey(status, date)}>
      <tr className="date-group-row" data-status={status} data-date={date} data-count={rows.length}><td colSpan="6">{collapsible ? <button onClick={() => setOpenDates(values => ({ ...values, [groupKey(status, date)]: !values[groupKey(status, date)] }))}><span>{openDates[groupKey(status, date)] === false ? '›' : '⌄'}</span><span className="date-label">▦ {status === 'done' ? '완료일 ' : ''}{formatDate(date)}</span><em>{rows.length}</em></button> : <div><span className="date-label">▦ {status === 'done' ? '완료일 ' : ''}{formatDate(date)}</span><em>{rows.length}</em></div>}</td></tr>
      {(!collapsible || openDates[groupKey(status, date)] !== false) && rows.map((item, rowIndex) => <WorklogRow key={item.id} id={status === 'done' && groupIndex === 0 && rowIndex === 0 ? 'latest-done-content' : undefined} item={item} data={data} dark={dark} onRequest={openRequestEditor} onProcessing={openProcessing} onRemove={remove}/>)}</Fragment>)
  }
  return <main className={`page${legacyMode ? ' legacy-mode' : ''}`}>
    <header className="title-bar"><div className="brand-title"><img src="/SRGH_logo.ico" alt="SRGH 로고"/><span><small>SRGH IT Team</small><h1 onClick={() => { window.location.href = '/admin' }}>{ko.title}</h1></span></div><div className="table-toolbar"><div className="main-filter-controls"><span className="header-period-actions"><button onClick={() => updateFilters({ from: moveDateBack(filters.from, 1) })}>-1일</button><button onClick={() => updateFilters({ from: moveDateBack(filters.from, 7) })}>-1주</button><button onClick={() => updateFilters({ from: moveDateBack(filters.from, 0, 1) })}>-1달</button><button onClick={() => updateFilters({ from: moveDateBack(filters.from, 0, 0, 1) })}>-1년</button></span><FilterForm filters={filters} data={data} processors={data.processors} onChange={updateFilters} live/><button className="header-filter-reset" onClick={resetFilters} title="필터 초기화">↻</button></div><button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>맨 위로</button><button onClick={() => document.getElementById('latest-done-content')?.scrollIntoView({ behavior: 'smooth', block: 'start' })}>완료로</button><button onClick={() => setFloating('meeting')}>회의록</button><button className="schedule-trigger" onClick={() => setFloating('schedule')}>월간 스케줄러{schedulePending > 0 && <em aria-label={`이번 달 미완료 ${schedulePending}건`}>{schedulePending}</em>}</button><button className="accent" onClick={() => setFloating('request')}>요청 생성</button></div></header>

    <section className="table-wrap">
      {legacyMode ? <LegacyTable items={data.items} data={data} dark={dark} onRequest={openRequestEditor} onProcessing={openProcessing} onRemove={remove} onSettings={() => setFloating('settings')}/> : <>
      <table><colgroup><col className="status-col"/><col className="category-col"/><col className="department-col"/><col className="request-content-col"/><col className="processor-col"/><col className="processing-content-col"/></colgroup><thead><tr><th className="settings-header-cell" onClick={() => setFloating('settings')} title="화면 설정" aria-label="화면 설정">⚙</th><th>카테고리 · 날짜</th><th>부서 · 요청자</th><th>{ko.content}</th><th>{ko.processor}</th><th>처리 내용</th></tr></thead>
        <tbody>
          {groups.progress.length > 0 && <tr className="status-section"><td colSpan="6"><div className="status-heading"><span>◷</span> 진행중 <em>{groups.progress.length}</em></div></td></tr>}
          {renderRows('progress', groups.progress, false, false)}
          {groups.done.length > 0 && <tr id="done-list" className="status-section done-section"><td colSpan="6"><div className="status-heading done"><span>✓</span><span className="done-title">처리완료</span><span ref={doneStickyLabel} className="done-sticky-date"></span><em ref={doneStickyCount} className="done-sticky-count"></em></div></td></tr>}
          {renderRows('done', groups.done, false)}
        </tbody>
      </table></>}
    </section>
    <div ref={loadMoreRef} className="load-more-sentinel" aria-hidden="true"/>
    {floating === 'request' && <FloatingWindow id="request" title="요청 생성" position={floatingPosition} onPositionChange={setFloatingPosition} onClose={() => setFloating(null)}><RequestForm data={data} clientId={clientId.current} onSubmitting={() => { pendingLocalMutation.current = true }} onSaved={() => setFloating(null)} onPersisted={applySavedItem}/></FloatingWindow>}
    {floating === 'meeting' && <FloatingWindow id="meeting" title="회의록 작성" position={floatingPosition} onPositionChange={setFloatingPosition} onClose={() => setFloating(null)}><MeetingForm processors={data.processors} onDone={() => setFloating(null)}/></FloatingWindow>}
    {floating === 'schedule' && <FloatingWindow id="schedule" title="월간 스케줄러" position={floatingPosition} onPositionChange={setFloatingPosition} onClose={() => setFloating(null)}><ScheduleQuickForm onItemsChange={items => setSchedulePending(currentMonthSchedulePending(items))}/></FloatingWindow>}
    {floating === 'settings' && <FloatingWindow id="settings" title="화면 설정" position={floatingPosition} onPositionChange={setFloatingPosition} onClose={() => setFloating(null)}><SettingsForm fontScale={fontScale} setFontScale={setFontScale} dark={dark} setDark={setDark} legacyMode={legacyMode} setLegacyMode={setLegacyMode} onResetFloatingPosition={() => setFloatingPosition(null)}/></FloatingWindow>}
    {floating === 'request-edit' && editingRequest && <FloatingWindow id="request-edit" title="요청 수정" position={floatingPosition} onPositionChange={setFloatingPosition} onClose={() => { setFloating(null); setEditingRequest(null) }}><RequestForm key={editingRequest.id} data={data} item={editingRequest} clientId={clientId.current} onSubmitting={() => { pendingLocalMutation.current = true }} onSaved={() => { setFloating(null); setEditingRequest(null) }} onPersisted={applySavedItem}/></FloatingWindow>}
    {floating === 'processing' && processing && <FloatingWindow id="processing" title="요청 처리" position={floatingPosition} onPositionChange={setFloatingPosition} onClose={() => { setFloating(null); setProcessing(null) }}><ProcessingForm key={processing.id} item={processing} processors={data.processors} clientId={clientId.current} onSubmitting={() => { pendingLocalMutation.current = true }} onSaved={() => { setFloating(null); setProcessing(null) }} onPersisted={applySavedItem}/></FloatingWindow>}
  </main>
}

function groupItems(items) { return { progress: items.filter(item => !item.processing_date), done: items.filter(item => item.processing_date) } }
function groupByDate(items) { return items.reduce((all, item) => { const date = item.processing_date || item.timestamp?.slice(0, 10) || item.request_date; (all[date] ||= []).push(item); return all }, {}) }
function WorklogRow({ id, item, data, dark, onRequest, onProcessing, onRemove }) { const pointerStart = useRef(null); const rememberPointer = event => { pointerStart.current = { x: event.clientX, y: event.clientY } }; const wasDragged = event => { const start = pointerStart.current; return start && (Math.abs(event.clientX - start.x) > 5 || Math.abs(event.clientY - start.y) > 5) }; const followTooltip = event => { event.currentTarget.style.setProperty('--tooltip-x', `${event.clientX + 14}px`); event.currentTarget.style.setProperty('--tooltip-y', `${event.clientY + 16}px`) }; const openRequest = event => { if (!wasDragged(event)) onRequest(event, item) }; const openProcessing = event => { if (!wasDragged(event)) onProcessing(event, item) }; return <tr id={id} className={item.processing_date ? 'completed-row' : 'in-progress-row'}>
  <td><button className={`status-icon ${item.processing_date ? 'done' : 'progress'}`} onClick={event => { event.stopPropagation(); onRemove(item.id) }} title="삭제">{item.processing_date ? '✓' : '◷'}</button></td>
  <td className="editable-cell" onPointerDown={rememberPointer} onPointerMove={followTooltip} onClick={openRequest}><button className="category-tooltip"><strong>{data.majorNames[item.major_category]}</strong><small>{data.minorNames[item.minor_category]}</small><span className="tooltip-content"><b>요청 날짜</b>{formatDate(item.request_date)}<b>수정 날짜</b>{formatTimestamp(item.timestamp)}<b>처리 날짜</b>{formatDate(item.processing_date)}</span></button></td>
  <td className="editable-cell department-person" onPointerDown={rememberPointer} onPointerMove={followTooltip} onClick={openRequest}><button className="requester-tooltip"><span className="department-line">{data.departmentNames[item.department]}</span><strong className="requester-name">{item.requester}</strong><span className="tooltip-content"><b>{ko.extension}</b>{item.requester_extension}</span></button></td>
  <td className="content important editable-cell" onPointerDown={rememberPointer} onClick={openRequest}><button>{item.request_content}</button></td>
  <td className="editable-cell" onPointerDown={rememberPointer} onClick={openProcessing}><button className="processor-name" style={{ '--processor-highlight': processorHighlight(data.processorNames[item.processor], dark) }}>{item.processor ? data.processorNames[item.processor] : ''}</button></td>
  <td className="content important editable-cell" onPointerDown={rememberPointer} onClick={openProcessing}><button>{item.processing_content || ''}</button></td>
</tr> }

function LegacyTable({ items, data, dark, onRequest, onProcessing, onRemove, onSettings }) {
  useEffect(() => {
    const row = document.querySelector('.legacy-table .legacy-done')
    if (row) row.id = 'latest-done-content'
    return () => { if (row?.id === 'latest-done-content') row.removeAttribute('id') }
  }, [items])
  return <table className="legacy-table"><thead><tr><th>타임스탬프</th><th>요청 날짜</th><th>메인 카테고리</th><th>서브 카테고리</th><th>부서</th><th>요청자</th><th>내선 번호</th><th>요청 내용</th><th>처리 날짜</th><th>처리자</th><th>처리 내용</th><th className="settings-header-cell legacy-settings-header" onClick={onSettings} title="화면 설정" aria-label="화면 설정">⚙</th></tr></thead><tbody>{items.map(item => <LegacyRow key={item.id} item={item} data={data} dark={dark} onRequest={onRequest} onProcessing={onProcessing} onRemove={onRemove}/>)}</tbody></table>
}

function LegacyRow({ item, data, dark, onRequest, onProcessing, onRemove }) {
  const pointerStart = useRef(null)
  const rememberPointer = event => { pointerStart.current = { x: event.clientX, y: event.clientY } }
  const wasDragged = event => { const start = pointerStart.current; return start && (Math.abs(event.clientX - start.x) > 5 || Math.abs(event.clientY - start.y) > 5) }
  const openRequest = event => { if (!wasDragged(event)) onRequest(event, item) }
  const openProcessing = event => { if (!wasDragged(event)) onProcessing(event, item) }
  const formatTimestamp = formatLegacyTimestamp
  const processorHighlight = legacyProcessorHighlight
  return <tr className={`legacy-row${item.processing_date ? ' legacy-done' : ' legacy-progress'}`}>
    <td onPointerDown={rememberPointer} onClick={openRequest}>{formatTimestamp(item.timestamp)}</td><td onPointerDown={rememberPointer} onClick={openRequest}>{formatDate(item.request_date)}</td><td onPointerDown={rememberPointer} onClick={openRequest}>{data.majorNames[item.major_category] || ''}</td><td onPointerDown={rememberPointer} onClick={openRequest}>{data.minorNames[item.minor_category] || ''}</td><td onPointerDown={rememberPointer} onClick={openRequest}>{data.departmentNames[item.department] || ''}</td><td onPointerDown={rememberPointer} onClick={openRequest}>{item.requester}</td><td onPointerDown={rememberPointer} onClick={openRequest}>{item.requester_extension}</td><td className="legacy-content-cell" onPointerDown={rememberPointer} onClick={openRequest}><button>{item.request_content}</button></td><td onPointerDown={rememberPointer} onClick={openProcessing}>{item.processing_date ? formatDate(item.processing_date) : ''}</td><td onPointerDown={rememberPointer} onClick={openProcessing}><button className="processor-name" style={{ '--processor-highlight': processorHighlight(data.processorNames[item.processor], dark) }}>{item.processor ? data.processorNames[item.processor] : ''}</button></td><td className="legacy-content-cell" onPointerDown={rememberPointer} onClick={openProcessing}><button>{item.processing_content || ''}</button></td><td className="legacy-actions"><button type="button" onClick={event => { event.stopPropagation(); onRemove(item.id) }} title="삭제">×</button></td>
  </tr>
}

function FloatingWindow({ id, title, headerAction, children, position, onPositionChange, onClose }) { const centered = id === 'settings', centerPosition = { x: Math.max(40, window.innerWidth / 2 - 180), y: Math.max(72, window.innerHeight / 2 - 150) }, defaultPosition = centered ? centerPosition : (position || centerPosition), node = useRef(null), current = useRef(defaultPosition), drag = useRef(null), frame = useRef(0); useEffect(() => { const next = keepFloatingVisible(centered ? centerPosition : (position || defaultPosition), node.current); current.current = next; if (node.current) Object.assign(node.current.style, { left: `${next.x}px`, top: `${next.y}px` }) }, [id, position, centered]); const move = event => { if (!drag.current || frame.current) return; const pointer = { x: event.clientX, y: event.clientY }; frame.current = requestAnimationFrame(() => { const next = keepFloatingVisible({ x: pointer.x - drag.current.x, y: pointer.y - drag.current.y }, node.current); current.current = next; Object.assign(node.current.style, { left: `${next.x}px`, top: `${next.y}px` }); frame.current = 0 }) }; const stop = () => { drag.current = null; cancelAnimationFrame(frame.current); frame.current = 0; onPositionChange(current.current); window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop) }; const start = event => { if (centered) return; drag.current = { x: event.clientX - current.current.x, y: event.clientY - current.current.y }; window.addEventListener('pointermove', move, { passive: true }); window.addEventListener('pointerup', stop) }; return <section ref={node} className={`floating-window${centered ? ' centered-floating' : ''}`} style={{ left: defaultPosition.x, top: defaultPosition.y }}><div className="floating-head" onPointerDown={start}><h2>{title}</h2><div className="floating-actions">{headerAction}<button onPointerDown={event => event.stopPropagation()} onClick={onClose} aria-label="닫기">×</button></div></div><div className="floating-body">{children}</div></section> }
function FilterForm({ filters, data, processors, onChange, live = false }) { const changeProcessor = event => { const value = event.target.value; onChange({ processor: value === '__placeholder__' || value === '' ? '' : value }) }; return <div className="filters"><DateRangePicker from={filters.from} to={filters.to} onChange={(from, to) => onChange({ from, to })} live={live}/><select aria-label="처리자" value={filters.processor || '__placeholder__'} onChange={changeProcessor}><option value="__placeholder__">처리자</option><option value="">전체</option>{processors.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><input aria-label="검색어" value={filters.keyword} onChange={event => onChange({ keyword: event.target.value })} placeholder="검색"/></div> }
function SettingsForm({ fontScale, setFontScale, dark, setDark, legacyMode, setLegacyMode, onResetFloatingPosition }) { const resize = event => { const value = Number(event.target.value); document.documentElement.style.setProperty('--app-font-scale', `${value / 100}`); setFontScale(value) }; return <div className="settings-form"><label>글씨 크기 <output>{fontScale}%</output><input type="range" min="100" max="140" step="5" value={fontScale} onChange={resize}/></label><button type="button" className="settings-theme-button" onClick={() => setLegacyMode(!legacyMode)}>{legacyMode ? '모던모드' : '레거시모드'}</button><button type="button" className="settings-theme-button" onClick={onResetFloatingPosition}>플로팅창 위치 초기화</button><button type="button" className="settings-theme-button" onClick={() => setDark(!dark)}>{dark ? '☀ 라이트모드' : '☾ 다크모드'}</button></div> }
function DateRangePicker({ from, to, onChange, live = false }) { const [open, setOpen] = useState(false), [leftMonth, setLeftMonth] = useState(() => new Date()), [rightMonth, setRightMonth] = useState(() => addMonths(new Date(), 1)), [draftFrom, setDraftFrom] = useState(from), [draftTo, setDraftTo] = useState(to), ref = useRef(null); useEffect(() => { const close = event => { if (open && !ref.current?.contains(event.target)) setOpen(false) }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close) }, [open]); const isManualDate = value => !value || (/^\d{4}-\d{2}-\d{2}$/.test(value) && localDate(new Date(`${value}T00:00:00`)) === value); const choose = value => { if (!draftFrom || draftTo || value < draftFrom) { setDraftFrom(value); setDraftTo(''); if (live) onChange(value, '') } else { setDraftTo(value); if (live) onChange(draftFrom, value) } }; const updateFrom = value => { setDraftFrom(value); if (live && isManualDate(value)) onChange(value, draftTo) }; const updateTo = value => { setDraftTo(value); if (live && isManualDate(value)) onChange(draftFrom, value) }; const clearForTyping = event => { event.currentTarget.value = '' }; return <div className="range-picker" ref={ref}><button type="button" className="range-button" onClick={() => { setDraftFrom(from); setDraftTo(to); setOpen(!open) }}><span>{formatDate(from)} ~ {formatDate(to)}</span><span>▦</span></button>{open && <div className="calendar-popover"><div className="calendar-title">날짜 범위 선택</div><div className="calendar-pair"><Calendar month={leftMonth} from={draftFrom} to={draftTo} onChoose={choose} onPrevious={() => setLeftMonth(addMonths(leftMonth, -1))} onNext={() => setLeftMonth(addMonths(leftMonth, 1))}/><Calendar month={rightMonth} from={draftFrom} to={draftTo} onChoose={choose} onPrevious={() => setRightMonth(addMonths(rightMonth, -1))} onNext={() => setRightMonth(addMonths(rightMonth, 1))}/></div><div className="manual-range"><input type="text" inputMode="numeric" autoComplete="off" placeholder="YYYY-MM-DD" value={draftFrom} onFocus={clearForTyping} onChange={event => updateFrom(event.target.value)}/><span>~</span><input type="text" inputMode="numeric" autoComplete="off" placeholder="YYYY-MM-DD" value={draftTo} onFocus={clearForTyping} onChange={event => updateTo(event.target.value)}/></div><div className="calendar-actions"><button type="button" className="clear-range" onClick={() => { const nextFrom = monthAgo(), nextTo = today(); setDraftFrom(nextFrom); setDraftTo(nextTo); if (live) onChange(nextFrom, nextTo) }}>초기화</button><button type="button" className="confirm-range" onClick={() => { if (!isManualDate(draftFrom) || !isManualDate(draftTo)) return; onChange(draftFrom, draftTo); setOpen(false) }}>확인</button></div></div>}</div> }
function Calendar({ month, from, to, onChoose, onPrevious, onNext }) { const first = new Date(month.getFullYear(), month.getMonth(), 1), last = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(), cells = Array(first.getDay()).fill(null).concat(Array.from({ length: last }, (_, index) => new Date(month.getFullYear(), month.getMonth(), index + 1))); return <div className="calendar"><div className="calendar-month-nav"><button type="button" aria-label="이전 달" onClick={onPrevious}>‹</button><b>{month.getFullYear()}.{String(month.getMonth() + 1).padStart(2, '0')}</b><button type="button" aria-label="다음 달" onClick={onNext}>›</button></div><div className="weekdays">{'SMTWTFS'.split('').map((day, index) => <span key={`${day}${index}`}>{day}</span>)}</div><div className="days">{cells.map((day, index) => { if (!day) return <i key={index}/>; const value = localDate(day), selected = value === from || value === to, inRange = from && to && value > from && value < to; return <button type="button" key={value} className={`${selected ? 'selected' : ''} ${inRange ? 'in-range' : ''}`} onClick={() => onChoose(value)}>{day.getDate()}</button> })}</div></div> }
function CategoryField({ label, options, value, setValue }) { return <label>{label}<select value={value} onChange={event => setValue(event.target.value)} required><option value="">선택하세요</option>{options.map(option => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label> }
function RequestForm({ data, item, clientId, onSubmitting, onSaved, onPersisted }) { const initial = item ? { request_date: item.request_date, major_category: String(item.major_category), minor_category: String(item.minor_category), department: String(item.department), requester: item.requester, requester_extension: item.requester_extension, request_content: item.request_content } : emptyCreate(); const [form, setForm] = useState(initial); const update = (key, value) => setForm({ ...form, [key]: value }); const submit = event => { event.preventDefault(); onSubmitting(); onSaved(); void fetch(item ? `/api/worklogs/${item.id}` : '/api/worklogs', { method: item ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json', 'X-Worklog-Client': clientId }, body: JSON.stringify(form) }).then(async response => { if (!response.ok) return alert('요청 저장에 실패했습니다.'); onPersisted(await response.json()) }).catch(() => alert('요청 저장에 실패했습니다.')) }; return <form className="create-form" onSubmit={submit}><label>{ko.date}<input type="date" value={form.request_date} onChange={event => update('request_date', event.target.value)} required/></label><CategoryField label={ko.major} options={data.majors} value={form.major_category} setValue={value => update('major_category', value)}/><CategoryField label={ko.minor} options={data.minors} value={form.minor_category} setValue={value => update('minor_category', value)}/><CategoryField label={ko.department} options={data.departments} value={form.department} setValue={value => update('department', value)}/><label>{ko.requester}<input value={form.requester} onChange={event => update('requester', event.target.value)} required/></label><label>{ko.extension}<input value={form.requester_extension} onChange={event => update('requester_extension', event.target.value)} required/></label><label>{ko.content}<textarea className="work-content-input" value={form.request_content} onChange={event => update('request_content', event.target.value)} required/></label><div className="actions"><button className="primary">{ko.complete}</button></div></form> }
function ProcessingForm({ item, processors, clientId, onSubmitting, onSaved, onPersisted }) { const [form, setForm] = useState({ processor: item.processor || '', processing_date: item.processing_date || today(), processing_content: item.processing_content || '' }); const submit = event => { event.preventDefault(); const payload = { ...form, processor: form.processor ? Number(form.processor) : null, processing_date: form.processing_date || null }; onSubmitting(); onSaved(); void fetch(`/api/worklogs/${item.id}/processing`, { method: 'PUT', headers: { 'Content-Type': 'application/json', 'X-Worklog-Client': clientId }, body: JSON.stringify(payload) }).then(async response => { if (!response.ok) return alert('저장에 실패했습니다.'); onPersisted(await response.json()) }).catch(() => alert('저장에 실패했습니다.')) }; return <form className="create-form" onSubmit={submit}><label>처리 날짜<input type="date" value={form.processing_date} onChange={event => setForm({ ...form, processing_date: event.target.value })}/></label><label>{ko.processor}<select value={form.processor} onChange={event => setForm({ ...form, processor: event.target.value })}><option value="">미지정</option>{processors.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>처리 내용<textarea className="work-content-input" value={form.processing_content} onChange={event => setForm({ ...form, processing_content: event.target.value })}/></label><div className="actions"><button className="primary">{ko.complete}</button></div></form> }
function MeetingForm({ processors, onDone }) { const [date, setDate] = useState(today()), [author, setAuthor] = useState(''), [notice, setNotice] = useState(''), [absenceReason, setAbsenceReason] = useState(''), [attendees, setAttendees] = useState(() => processors.map(p => ({ name: p.name, present: true }))); const save = async event => { event.preventDefault(); const response = await fetch('/api/worklogs/meeting-minutes/pdf', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ meeting_date: date, author, attendees: attendees.map(a => ({ ...a, reason: a.present ? '' : absenceReason })), notice }) }); if (!response.ok) return alert('PDF 생성에 실패했습니다.'); const url = URL.createObjectURL(await response.blob()), link = document.createElement('a'); link.href = url; link.download = `IT팀_${date.replaceAll('-', '.')}.pdf`; link.click(); URL.revokeObjectURL(url); onDone() }; return <form className="create-form" onSubmit={save}><label>회의 날짜<input type="date" value={date} onChange={event => setDate(event.target.value)} required/></label><label>작성자<select value={author} onChange={event => setAuthor(event.target.value)} required><option value="">선택하세요</option>{processors.map(p => <option key={p.id} value={p.name}>{p.name}</option>)}</select></label><label>참석자<div className="attendees">{attendees.map((a, index) => <div className="attendee-row" key={a.name}><span>{a.name}</span><button type="button" className={a.present ? 'attendance present' : 'attendance absent'} onClick={() => setAttendees(attendees.map((entry, i) => i === index ? { ...entry, present: !entry.present } : entry))}>{a.present ? '참석' : '불참'}</button></div>)}</div></label><label>결석 사유<input value={absenceReason} onChange={event => setAbsenceReason(event.target.value)}/></label><label>알림사항<textarea value={notice} onChange={event => setNotice(event.target.value)}/></label><div className="actions"><button className="primary">{ko.complete}</button></div></form> }

createRoot(document.getElementById('root')).render(window.location.pathname === '/admin' ? <CatalogManager/> : <App />)
