import { Fragment, useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './style.css'
import './meeting.css'
import { CatalogManager, ScheduleQuickForm } from './scheduler'

const ko = { title: '업무일지', filter: 'SRGH IT', request: '요청 생성', complete: '작성 완료', date: '날짜', processor: '처리자', keyword: '검색어', content: '요청 내용', requester: '요청자', extension: '내선 번호', department: '부서', major: '메인 카테고리', minor: '서브 카테고리' }
const localDate = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const today = () => localDate(new Date())
const threeMonthsAgo = () => { const value = new Date(); value.setMonth(value.getMonth() - 3); return localDate(value) }
const formatDate = value => value ? `${value.slice(2, 4)}.${value.slice(5, 7)}.${value.slice(8, 10)}` : '-'
const formatTimestamp = value => value ? new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Seoul', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: 'h23' }).format(new Date(value)) : '-'
const processorHighlight = (name, dark) => ({ 김재현: dark ? '#7f1d1d' : '#fecaca', 강성구: dark ? '#1e3a8a' : '#bfdbfe', 오세민: dark ? '#14532d' : '#bbf7d0', 최인호: dark ? '#581c87' : '#e9d5ff' }[name] || (dark ? '#334155' : '#e2e8f0'))
const addMonths = (date, amount) => new Date(date.getFullYear(), date.getMonth() + amount, 1)
const emptyCreate = () => ({ request_date: today(), major_category: '', minor_category: '', department: '', requester: '', requester_extension: '', request_content: '' })

function App() {
  const [data, setData] = useState(null)
  const [filters, setFilters] = useState({ from: threeMonthsAgo(), to: today(), processor: '', keyword: '', major: '', minor: '', department: '', requestContent: '' })
  const [dark, setDark] = useState(() => localStorage.getItem('worklog-dark-mode') === 'true')
  const [fontScale, setFontScale] = useState(() => {
    const saved = Number(localStorage.getItem('worklog-font-scale'))
    return Number.isFinite(saved) ? Math.min(140, Math.max(100, saved)) : 100
  })
  const [editingRequest, setEditingRequest] = useState(null)
  const [processing, setProcessing] = useState(null)
  const [floating, setFloating] = useState('filter')
  const [openDates, setOpenDates] = useState({})
  const doneStickyKey = useRef('')
  const doneStickyLabel = useRef(null)
  const doneStickyCount = useRef(null)
  const doneDateRows = useRef([])
  const [progressOpen, setProgressOpen] = useState(true)
  const [floatingPosition, setFloatingPosition] = useState(() => JSON.parse(localStorage.getItem('worklog-floating-position') || 'null'))
  const load = async (next = filters) => { const params = new URLSearchParams(Object.entries(next).filter(([, value]) => value !== '')); const response = await fetch(`/api/worklogs?${params}`, { cache: 'no-store' }); if (response.ok) setData(await response.json()) }

  useEffect(() => { load() }, [])
  useEffect(() => { const stream = new EventSource('/api/events/worklogs'); const refresh = () => load(); stream.addEventListener('worklog-update', refresh); return () => stream.close() }, [filters])
  useEffect(() => { document.body.classList.toggle('dark', dark); localStorage.setItem('worklog-dark-mode', dark) }, [dark])
  useEffect(() => { document.documentElement.style.setProperty('--app-font-scale', `${fontScale / 100}`); localStorage.setItem('worklog-font-scale', String(fontScale)) }, [fontScale])
  useEffect(() => { localStorage.setItem('worklog-floating-position', JSON.stringify(floatingPosition)) }, [floatingPosition])
  useEffect(() => { const close = event => { if (event.key === 'Escape' && floating && floating !== 'filter') setFloating('filter') }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [floating])
  useEffect(() => { let timer = 0; doneDateRows.current = [...document.querySelectorAll('.date-group-row[data-status="done"]')]; const update = () => { const completed = document.getElementById('done-list'), rows = doneDateRows.current; let active = null; if (completed && completed.getBoundingClientRect().top <= 130) { let low = 0, high = rows.length - 1; while (low <= high) { const middle = (low + high) >> 1; if (rows[middle].getBoundingClientRect().top <= 170) { active = rows[middle]; low = middle + 1 } else high = middle - 1 } } const key = active ? `${active.dataset.date}-${active.dataset.count}` : ''; if (key === doneStickyKey.current) return; doneStickyKey.current = key; if (doneStickyLabel.current) { doneStickyLabel.current.textContent = active ? `▦ ${formatDate(active.dataset.date)}` : ''; doneStickyLabel.current.classList.toggle('visible', Boolean(active)) } if (doneStickyCount.current) doneStickyCount.current.textContent = active ? active.dataset.count : '' }; const schedule = () => { clearTimeout(timer); timer = setTimeout(update, 140) }; update(); window.addEventListener('scroll', schedule, { passive: true }); return () => { window.removeEventListener('scroll', schedule); clearTimeout(timer) } }, [data])

  const updateFilters = patch => { const next = { ...filters, ...patch }; setFilters(next); load(next) }
  const resetFilters = () => updateFilters({ from: threeMonthsAgo(), to: today(), processor: '', keyword: '', major: '', minor: '', department: '', requestContent: '' })
  const openCellFilter = patch => { updateFilters(patch); setFloating('filter') }
  const openRequestEditor = (event, item) => { event.stopPropagation(); setEditingRequest(item); setProcessing(null); setFloating('request-edit') }
  const openProcessing = (event, item) => { event.stopPropagation(); setProcessing(item); setEditingRequest(null); setFloating('processing') }
  const remove = async id => { if (!confirm('이 요청을 삭제할까요?')) return; await fetch(`/api/worklogs/${id}`, { method: 'DELETE' }); load() }
  const groups = useMemo(() => groupItems(data?.items || []), [data])
  if (!data) return <div className="loading">불러오는 중…</div>

  const groupKey = (status, date) => `${status}-${date}`
  const renderRows = (status, items, collapsible = true, showDate = true) => {
    if (!showDate) return items.map(item => <WorklogRow key={item.id} item={item} data={data} dark={dark} onRequest={openRequestEditor} onProcessing={openProcessing} onRemove={remove} onFilter={openCellFilter}/>)
    const byDate = groupByDate(items)
    return Object.entries(byDate).map(([date, rows], groupIndex) => <Fragment key={groupKey(status, date)}>
      <tr className="date-group-row" data-status={status} data-date={date} data-count={rows.length}><td colSpan="6">{collapsible ? <button onClick={() => setOpenDates(values => ({ ...values, [groupKey(status, date)]: !values[groupKey(status, date)] }))}><span>{openDates[groupKey(status, date)] === false ? '›' : '⌄'}</span><span className="date-label">▦ {formatDate(date)}</span><em>{rows.length}</em></button> : <div><span className="date-label">▦ {formatDate(date)}</span><em>{rows.length}</em></div>}</td></tr>
      {(!collapsible || openDates[groupKey(status, date)] !== false) && rows.map((item, rowIndex) => <WorklogRow key={item.id} id={status === 'done' && groupIndex === 0 && rowIndex === 0 ? 'latest-done-content' : undefined} item={item} data={data} dark={dark} onRequest={openRequestEditor} onProcessing={openProcessing} onRemove={remove} onFilter={openCellFilter}/>)}</Fragment>)
  }
  return <main className="page">
    <header className="title-bar"><button className="brand-title" onClick={() => setFloating('filter')} title="필터 열기"><img src="/SRGH_logo.ico" alt="SRGH 로고"/><span><small>SRGH IT Team</small><h1 onClick={event => { event.stopPropagation(); window.location.href = '/admin' }}>{ko.title}</h1></span></button><div className="table-toolbar"><button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>맨 위로</button><button onClick={() => document.getElementById('latest-done-content')?.scrollIntoView({ behavior: 'smooth', block: 'start' })}>처리완료</button><button onClick={() => setFloating('meeting')}>회의록</button><button onClick={() => setFloating('schedule')}>월간 스케줄러</button><button onClick={() => setFloating('filter')}>필터</button><button className="accent" onClick={() => setFloating('request')}>요청 생성</button></div></header>

    <section className="table-wrap">
      <table><colgroup><col className="status-col"/><col className="category-col"/><col className="department-col"/><col className="request-content-col"/><col className="processor-col"/><col className="processing-content-col"/></colgroup><thead><tr><th onClick={() => setFloating('filter')}></th><th onClick={() => setFloating('filter')}><button className="column-filter">카테고리 · 날짜</button></th><th onClick={() => setFloating('filter')}>부서 · 요청자</th><th onClick={() => setFloating('filter')}>{ko.content}</th><th onClick={() => setFloating('filter')}>{ko.processor}</th><th onClick={() => setFloating('filter')}>처리 내용</th></tr></thead>
        <tbody>
          {groups.progress.length > 0 && <tr className="status-section"><td colSpan="6"><div className="status-heading"><span>◷</span> 진행중 <em>{groups.progress.length}</em></div></td></tr>}
          {renderRows('progress', groups.progress, false, false)}
          {groups.done.length > 0 && <tr id="done-list" className="status-section done-section"><td colSpan="6"><div className="status-heading done"><span>✓</span><span className="done-title">처리완료</span><span ref={doneStickyLabel} className="done-sticky-date"></span><em ref={doneStickyCount} className="done-sticky-count"></em></div></td></tr>}
          {renderRows('done', groups.done, false)}
        </tbody>
      </table>
    </section>
    {floating === 'filter' && <FloatingWindow id="filter" title="필터" headerAction={<><input className="floating-font-range" onPointerDown={event => event.stopPropagation()} type="range" min="100" max="140" step="5" value={fontScale} onChange={event => { const value = Number(event.target.value); document.documentElement.style.setProperty('--app-font-scale', `${value / 100}`); setFontScale(value) }}/><output className="floating-font-value">{fontScale}%</output><button className="floating-reset-toggle" onPointerDown={event => event.stopPropagation()} onClick={resetFilters} title="필터 초기화">↻</button><button className="floating-theme-toggle" onPointerDown={event => event.stopPropagation()} onClick={() => setDark(!dark)} title={dark ? '라이트모드' : '다크모드'}>{dark ? '☀' : '☾'}</button></>} position={floatingPosition} onPositionChange={setFloatingPosition} onClose={() => setFloating(null)}><FilterForm filters={filters} data={data} processors={data.processors} onChange={updateFilters} fontScale={fontScale} setFontScale={setFontScale} live/></FloatingWindow>}
    {floating === 'request' && <FloatingWindow id="request" title="요청 생성" position={floatingPosition} onPositionChange={setFloatingPosition} onClose={() => setFloating(null)}><RequestForm data={data} onSaved={() => setFloating('filter')}/></FloatingWindow>}
    {floating === 'meeting' && <FloatingWindow id="meeting" title="회의록 작성" position={floatingPosition} onPositionChange={setFloatingPosition} onClose={() => setFloating(null)}><MeetingForm processors={data.processors} onDone={() => setFloating('filter')}/></FloatingWindow>}
    {floating === 'schedule' && <FloatingWindow id="schedule" title="월간 스케줄러" position={floatingPosition} onPositionChange={setFloatingPosition} onClose={() => setFloating(null)}><ScheduleQuickForm/></FloatingWindow>}
    {floating === 'request-edit' && editingRequest && <FloatingWindow id="request-edit" title="요청 수정" position={floatingPosition} onPositionChange={setFloatingPosition} onClose={() => { setFloating(null); setEditingRequest(null) }}><RequestForm key={editingRequest.id} data={data} item={editingRequest} onSaved={() => { setFloating('filter'); setEditingRequest(null) }}/></FloatingWindow>}
    {floating === 'processing' && processing && <FloatingWindow id="processing" title="요청 처리" position={floatingPosition} onPositionChange={setFloatingPosition} onClose={() => { setFloating(null); setProcessing(null) }}><ProcessingForm key={processing.id} item={processing} processors={data.processors} onSaved={() => { setFloating('filter'); setProcessing(null) }}/></FloatingWindow>}
  </main>
}

function groupItems(items) { return { progress: items.filter(item => !item.processing_date), done: items.filter(item => item.processing_date) } }
function groupByDate(items) { return items.reduce((all, item) => { const date = item.processing_date || item.timestamp?.slice(0, 10) || item.request_date; (all[date] ||= []).push(item); return all }, {}) }
function WorklogRow({ id, item, data, dark, onRequest, onProcessing, onRemove, onFilter }) { const followTooltip = event => { event.currentTarget.style.setProperty('--tooltip-x', `${event.clientX + 14}px`); event.currentTarget.style.setProperty('--tooltip-y', `${event.clientY + 16}px`) }; return <tr id={id} className={item.processing_date ? 'completed-row' : 'in-progress-row'}>
  <td><button className={`status-icon ${item.processing_date ? 'done' : 'progress'}`} onClick={event => { event.stopPropagation(); onRemove(item.id) }} title="삭제">{item.processing_date ? '✓' : '◷'}</button></td>
  <td className="editable-cell" onPointerMove={followTooltip} onClick={event => onRequest(event, item)}><button className="category-tooltip"><strong>{data.majorNames[item.major_category]}</strong><small>{data.minorNames[item.minor_category]}</small><span className="tooltip-content"><b>요청 날짜</b>{formatDate(item.request_date)}<b>수정 날짜</b>{formatTimestamp(item.timestamp)}<b>처리 날짜</b>{formatDate(item.processing_date)}</span></button></td>
  <td className="editable-cell department-person" onPointerMove={followTooltip} onClick={event => onRequest(event, item)}><button className="requester-tooltip"><span className="department-line">{data.departmentNames[item.department]}</span><strong className="requester-name">{item.requester}</strong><span className="tooltip-content"><b>{ko.extension}</b>{item.requester_extension}</span></button></td>
  <td className="content important editable-cell" onClick={event => onRequest(event, item)}><button>{item.request_content}</button></td>
  <td className="editable-cell" onClick={event => onProcessing(event, item)}><button className="processor-name" style={{ '--processor-highlight': processorHighlight(data.processorNames[item.processor], dark) }}>{item.processor ? data.processorNames[item.processor] : ''}</button></td>
  <td className="content important editable-cell" onClick={event => onProcessing(event, item)}><button>{item.processing_content || ''}</button></td>
</tr> }

function FloatingWindow({ id, title, headerAction, children, position, onPositionChange, onClose }) { const defaultPosition = position || { x: Math.max(40, window.innerWidth / 2 - 180), y: 100 }, node = useRef(null), current = useRef(defaultPosition), drag = useRef(null), frame = useRef(0); useEffect(() => { current.current = position || defaultPosition; if (node.current) Object.assign(node.current.style, { left: `${current.current.x}px`, top: `${current.current.y}px` }) }, [id]); const move = event => { if (!drag.current || frame.current) return; const pointer = { x: event.clientX, y: event.clientY }; frame.current = requestAnimationFrame(() => { const next = { x: Math.max(10, pointer.x - drag.current.x), y: Math.max(10, pointer.y - drag.current.y) }; current.current = next; Object.assign(node.current.style, { left: `${next.x}px`, top: `${next.y}px` }); frame.current = 0 }) }; const stop = () => { drag.current = null; cancelAnimationFrame(frame.current); frame.current = 0; onPositionChange(current.current); window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop) }; const start = event => { drag.current = { x: event.clientX - current.current.x, y: event.clientY - current.current.y }; window.addEventListener('pointermove', move, { passive: true }); window.addEventListener('pointerup', stop) }; return <section ref={node} className="floating-window" style={{ left: defaultPosition.x, top: defaultPosition.y }}><div className="floating-head" onPointerDown={start}><h2>{title}</h2><div className="floating-actions">{headerAction}<button onPointerDown={event => event.stopPropagation()} onClick={onClose} aria-label="닫기">×</button></div></div><div className="floating-body">{children}</div></section> }
function FilterForm({ filters, data, processors, onChange, fontScale, setFontScale, live = false }) { const resize = event => { const value = Number(event.target.value); document.documentElement.style.setProperty('--app-font-scale', `${value / 100}`); setFontScale(value) }; return <div className="filters"><label>조회 기간<DateRangePicker from={filters.from} to={filters.to} onChange={(from, to) => onChange({ from, to })} live={live}/></label><label>메인 카테고리<select value={filters.major} onChange={event => onChange({ major: event.target.value, minor: '' })}><option value="">전체</option>{data.majors.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>서브 카테고리<select value={filters.minor} onChange={event => onChange({ minor: event.target.value })}><option value="">전체</option>{data.minors.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>부서<select value={filters.department} onChange={event => onChange({ department: event.target.value })}><option value="">전체</option>{data.departments.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{ko.processor}<select value={filters.processor} onChange={event => onChange({ processor: event.target.value })}><option value="">전체</option>{processors.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{ko.keyword}<input value={filters.keyword} onChange={event => onChange({ keyword: event.target.value })} placeholder="요청자, 내용 검색"/></label><label className="font-control">글씨 크기 <output>{fontScale}%</output><input type="range" min="100" max="140" step="5" value={fontScale} onChange={resize}/></label></div> }
function DateRangePicker({ from, to, onChange, live = false }) { const [open, setOpen] = useState(false), [month, setMonth] = useState(() => new Date()), [draftFrom, setDraftFrom] = useState(from), [draftTo, setDraftTo] = useState(to), ref = useRef(null); useEffect(() => { const close = event => { if (open && !ref.current?.contains(event.target)) setOpen(false) }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close) }, [open]); const choose = value => { if (!draftFrom || draftTo || value < draftFrom) { setDraftFrom(value); setDraftTo(''); if (live) onChange(value, '') } else { setDraftTo(value); if (live) onChange(draftFrom, value) } }; const updateFrom = value => { setDraftFrom(value); setDraftTo(''); if (live) onChange(value, '') }; const updateTo = value => { setDraftTo(value); if (live) onChange(draftFrom, value) }; return <div className="range-picker" ref={ref}><button type="button" className="range-button" onClick={() => { setDraftFrom(from); setDraftTo(to); setOpen(!open) }}><span>{formatDate(from)} ~ {formatDate(to)}</span><span>▦</span></button>{open && <div className="calendar-popover"><div className="calendar-nav"><button type="button" onClick={() => setMonth(addMonths(month, -1))}>‹</button><span>날짜 범위 선택</span><button type="button" onClick={() => setMonth(addMonths(month, 1))}>›</button></div><div className="calendar-pair"><Calendar month={month} from={draftFrom} to={draftTo} onChoose={choose}/><Calendar month={addMonths(month, 1)} from={draftFrom} to={draftTo} onChoose={choose}/></div><div className="manual-range"><input type="date" value={draftFrom} onChange={event => updateFrom(event.target.value)}/><span>~</span><input type="date" value={draftTo} min={draftFrom} onChange={event => updateTo(event.target.value)}/></div><div className="calendar-actions"><button type="button" className="clear-range" onClick={() => { const nextFrom = threeMonthsAgo(), nextTo = today(); setDraftFrom(nextFrom); setDraftTo(nextTo); if (live) onChange(nextFrom, nextTo) }}>초기화</button><button type="button" className="confirm-range" onClick={() => { onChange(draftFrom, draftTo); setOpen(false) }}>확인</button></div></div>}</div> }
function Calendar({ month, from, to, onChoose }) { const first = new Date(month.getFullYear(), month.getMonth(), 1), last = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(), cells = Array(first.getDay()).fill(null).concat(Array.from({ length: last }, (_, index) => new Date(month.getFullYear(), month.getMonth(), index + 1))); return <div className="calendar"><b>{month.getFullYear()}.{String(month.getMonth() + 1).padStart(2, '0')}</b><div className="weekdays">{'SMTWTFS'.split('').map((day, index) => <span key={`${day}${index}`}>{day}</span>)}</div><div className="days">{cells.map((day, index) => { if (!day) return <i key={index}/>; const value = localDate(day), selected = value === from || value === to, inRange = from && to && value > from && value < to; return <button type="button" key={value} className={`${selected ? 'selected' : ''} ${inRange ? 'in-range' : ''}`} onClick={() => onChoose(value)}>{day.getDate()}</button> })}</div></div> }
function CategoryField({ label, options, value, setValue }) { return <label>{label}<select value={value} onChange={event => setValue(event.target.value)} required><option value="">선택하세요</option>{options.map(option => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label> }
function RequestForm({ data, item, onSaved }) { const initial = item ? { request_date: item.request_date, major_category: String(item.major_category), minor_category: String(item.minor_category), department: String(item.department), requester: item.requester, requester_extension: item.requester_extension, request_content: item.request_content } : emptyCreate(); const [form, setForm] = useState(initial); const update = (key, value) => setForm({ ...form, [key]: value }); const submit = event => { event.preventDefault(); onSaved(); void fetch(item ? `/api/worklogs/${item.id}` : '/api/worklogs', { method: item ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }).then(response => { if (!response.ok) alert('요청 저장에 실패했습니다.') }).catch(() => alert('요청 저장에 실패했습니다.')) }; return <form className="create-form" onSubmit={submit}><label>{ko.date}<input type="date" value={form.request_date} onChange={event => update('request_date', event.target.value)} required/></label><CategoryField label={ko.major} options={data.majors} value={form.major_category} setValue={value => update('major_category', value)}/><CategoryField label={ko.minor} options={data.minors} value={form.minor_category} setValue={value => update('minor_category', value)}/><CategoryField label={ko.department} options={data.departments} value={form.department} setValue={value => update('department', value)}/><label>{ko.requester}<input value={form.requester} onChange={event => update('requester', event.target.value)} required/></label><label>{ko.extension}<input value={form.requester_extension} onChange={event => update('requester_extension', event.target.value)} required/></label><label>{ko.content}<textarea className="work-content-input" value={form.request_content} onChange={event => update('request_content', event.target.value)} required/></label><div className="actions"><button className="primary">{ko.complete}</button></div></form> }
function ProcessingForm({ item, processors, onSaved }) { const [form, setForm] = useState({ processor: item.processor || '', processing_date: item.processing_date || today(), processing_content: item.processing_content || '' }); const submit = event => { event.preventDefault(); const payload = { ...form, processor: form.processor ? Number(form.processor) : null, processing_date: form.processing_date || null }; onSaved(); void fetch(`/api/worklogs/${item.id}/processing`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }).then(response => { if (!response.ok) alert('저장에 실패했습니다.') }).catch(() => alert('저장에 실패했습니다.')) }; return <form className="create-form" onSubmit={submit}><label>처리 날짜<input type="date" value={form.processing_date} onChange={event => setForm({ ...form, processing_date: event.target.value })}/></label><label>{ko.processor}<select value={form.processor} onChange={event => setForm({ ...form, processor: event.target.value })}><option value="">미지정</option>{processors.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>처리 내용<textarea className="work-content-input" value={form.processing_content} onChange={event => setForm({ ...form, processing_content: event.target.value })}/></label><div className="actions"><button className="primary">{ko.complete}</button></div></form> }
function MeetingForm({ processors, onDone }) { const [date, setDate] = useState(today()), [author, setAuthor] = useState(''), [notice, setNotice] = useState(''), [absenceReason, setAbsenceReason] = useState(''), [attendees, setAttendees] = useState(() => processors.map(p => ({ name: p.name, present: true }))); const save = async event => { event.preventDefault(); const response = await fetch('/api/worklogs/meeting-minutes/pdf', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ meeting_date: date, author, attendees: attendees.map(a => ({ ...a, reason: a.present ? '' : absenceReason })), notice }) }); if (!response.ok) return alert('PDF 생성에 실패했습니다.'); const url = URL.createObjectURL(await response.blob()), link = document.createElement('a'); link.href = url; link.download = `IT팀_${date.replaceAll('-', '.')}.pdf`; link.click(); URL.revokeObjectURL(url); onDone() }; return <form className="create-form" onSubmit={save}><label>회의 날짜<input type="date" value={date} onChange={event => setDate(event.target.value)} required/></label><label>작성자<select value={author} onChange={event => setAuthor(event.target.value)} required><option value="">선택하세요</option>{processors.map(p => <option key={p.id} value={p.name}>{p.name}</option>)}</select></label><label>참석자<div className="attendees">{attendees.map((a, index) => <div className="attendee-row" key={a.name}><span>{a.name}</span><button type="button" className={a.present ? 'attendance present' : 'attendance absent'} onClick={() => setAttendees(attendees.map((entry, i) => i === index ? { ...entry, present: !entry.present } : entry))}>{a.present ? '참석' : '불참'}</button></div>)}</div></label><label>결석 사유<input value={absenceReason} onChange={event => setAbsenceReason(event.target.value)}/></label><label>알림사항<textarea value={notice} onChange={event => setNotice(event.target.value)}/></label><div className="actions"><button className="primary">{ko.complete}</button></div></form> }

createRoot(document.getElementById('root')).render(window.location.pathname === '/admin' ? <CatalogManager/> : <App />)
